import {CanvasFrameRenderer} from "../src/lib/renderer-canvas.js";
import {imageDataToTextFrame} from "../src/lib/convert.js";
import {PRESETS} from "../src/lib/presets.js";
import {DEFAULT_RECIPE,validateRecipe,parseRecipe,encodeRecipe,decodeRecipe} from "../src/lib/recipe.js";
import {cardSize,selectRecordingType,recordingFormat} from "../src/lib/motion.js";
const $=id=>document.getElementById(id),output=$("output"),video=$("video"),sample=$("sample-canvas"),renderer=new CanvasFrameRenderer(output),sampling=document.createElement("canvas");
let recipe=structuredClone(DEFAULT_RECIPE),source=sample,stream=null,frame="",recorder=null,timer=null,sourceUrl=null,resultUrl=null,loading=0;
const status=s=>$("status").textContent=s;
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
function savePng(){return new Promise((resolve,reject)=>output.toBlob(b=>{if(!b){reject(Error("PNGの保存に失敗しました"));return;}download(b,"text-video-art.png");resolve();},"image/png"));}
function readSettings(){recipe=validateRecipe({...recipe,preset:$("preset").value,columns:Number($("columns").value),charset:$("charset").value,invert:$("invert").checked,aspect_correction:Number($("aspect").value),theme:{foreground:$("foreground").value,background:$("background").value},fit:$("fit").value,motion:{...recipe.motion,aspect:$("ratio").value}});return recipe;}
function applySettings(){for(const [id,value] of Object.entries({preset:recipe.preset,columns:recipe.columns,charset:recipe.charset,aspect:recipe.aspect_correction,foreground:recipe.theme.foreground,background:recipe.theme.background,fit:recipe.fit,ratio:recipe.motion.aspect}))$(id).value=value;$("invert").checked=recipe.invert;}
function render(){if(document.hidden)return;try{const r=readSettings(),w=source===video?video.videoWidth:source.width,h=source===video?video.videoHeight:source.height;if(!w||!h)return;const rows=Math.max(1,Math.min(480,Math.round(r.columns*h/w*r.aspect_correction)));sampling.width=r.columns;sampling.height=rows;const c=sampling.getContext("2d",{willReadFrequently:true});c.fillStyle=r.theme.background;c.fillRect(0,0,r.columns,rows);c.drawImage(source,0,0,r.columns,rows);frame=imageDataToTextFrame(c.getImageData(0,0,r.columns,rows),r.columns,rows,r.charset,r.invert,r.preset);const size=cardSize(r.motion.aspect);if(output.width!==size.width||output.height!==size.height){output.width=size.width;output.height=size.height;}renderer.options={fit:r.fit,cellAspect:r.aspect_correction,foreground:r.theme.foreground,background:r.theme.background};renderer.render(frame);}catch(e){status(e.message);}}
function sampleImage(){sample.width=640;sample.height=480;const c=sample.getContext("2d");c.fillStyle="#162d3d";c.fillRect(0,0,640,480);const g=c.createRadialGradient(320,210,10,320,210,220);g.addColorStop(0,"#fff5c8");g.addColorStop(1,"#19313e");c.fillStyle=g;c.beginPath();c.arc(320,210,210,0,Math.PI*2);c.fill();c.strokeStyle="#fff5c8";c.lineWidth=5;for(let i=0;i<8;i++){c.beginPath();c.ellipse(320,250,220,30+i*12,(i-4)*0.12,0,Math.PI*2);c.stroke();}source=sample;render();status("手続き生成サンプル / MIT — 写真を選んで試せます");}
function stopRecording(){if(recorder?.state!=="inactive")recorder?.stop();}
function stopInput(){if(timer){clearInterval(timer);timer=null;}if(stream){stream.getTracks().forEach(t=>t.stop());stream=null;}video.pause();video.srcObject=null;if(sourceUrl){URL.revokeObjectURL(sourceUrl);sourceUrl=null;}video.removeAttribute("src");video.load();}
function startFrames(){if(timer)clearInterval(timer);timer=setInterval(render,1000/15);render();}
function guarded(fn){return async()=>{try{await fn();}catch(e){status(e.message);}};}
function setBusy(busy){for(const id of ["source","sample","camera","stop","preset","columns","foreground","background","fit","charset","aspect","invert","ratio","record","recipe-load"])$(id).disabled=busy;}
$("sample").onclick=()=>{loading++;stopInput();sampleImage();};
$("stop").onclick=()=>{loading++;stopInput();sampleImage();};
$("source").onchange=guarded(async()=>{const file=$("source").files?.[0];if(!file)return;if(file.size>64*1024*1024)throw Error("素材は64 MiB以下を選んでください");const token=++loading;stopInput();if(file.type.startsWith("video/")){sourceUrl=URL.createObjectURL(file);video.src=sourceUrl;await new Promise((resolve,reject)=>{video.onloadeddata=resolve;video.onerror=()=>reject(Error("この動画形式を再生できません。別の動画または写真を選んでください"));});if(token!==loading)return;source=video;video.loop=true;await video.play();startFrames();status("動画を表示中。Motion Cardは先頭の最大5秒を保存します");}else{const image=await createImageBitmap(file);if(token!==loading){image.close();return;}sample.width=image.width;sample.height=image.height;sample.getContext("2d").drawImage(image,0,0);image.close();source=sample;render();status("写真を変換しました");}});
$("camera").onclick=guarded(async()=>{if(!isSecureContext)throw Error("カメラにはHTTPSまたはlocalhostが必要です");if(!navigator.mediaDevices?.getUserMedia)throw Error("この環境ではカメラを使えません。写真を選んでください");const token=++loading;stopInput();status("カメラの許可を待っています");const media=await navigator.mediaDevices.getUserMedia({video:true,audio:false});if(token!==loading||document.hidden){media.getTracks().forEach(t=>t.stop());return;}stream=media;video.srcObject=media;try{await video.play();}catch(e){stopInput();throw e;}source=video;startFrames();status("カメラを表示中");});
for(const id of ["columns","foreground","background","fit","charset","aspect","invert","ratio"])$(id).oninput=render;
$("preset").onchange=()=>{const p=PRESETS[$("preset").value];$("charset").value=p.charset;$("foreground").value=p.foreground;$("background").value=p.background;render();};
$("copy").onclick=guarded(async()=>{if(!navigator.clipboard)throw Error("コピーできません。TXT保存を使ってください");await navigator.clipboard.writeText(frame+"\n");status("TXTをコピーしました");});
$("txt").onclick=()=>download(new Blob([frame+"\n"],{type:"text/plain;charset=utf-8"}),"text-video-art.txt");$("png").onclick=guarded(savePng);
$("recipe-save").onclick=guarded(()=>download(new Blob([JSON.stringify(readSettings(),null,2)+"\n"],{type:"application/json"}),"tvart-recipe.json"));
$("recipe-load").onchange=guarded(async()=>{const file=$("recipe-load").files?.[0];if(!file)return;if(file.size>8192)throw Error("レシピが大きすぎます");recipe=parseRecipe(new TextDecoder("utf-8",{fatal:true}).decode(await file.arrayBuffer()));applySettings();render();status("設定を読み込みました。素材は現在のままです");});
$("share").onclick=guarded(async()=>{const url=new URL(location.href);url.search="";url.hash="recipe="+encodeRecipe(readSettings());$("share-url").hidden=false;$("share-url").value=url.href;$("share-url").select();try{await navigator.clipboard.writeText(url.href);status("設定リンクをコピーしました（素材は含みません）");}catch{status("表示された設定リンクをコピーしてください（素材は含みません）");}});
$("record").onclick=guarded(async()=>{
 if(recorder)return;const type=selectRecordingType(globalThis.MediaRecorder);if(!type||!output.captureStream){await savePng();status("録画非対応のためPNGを保存しました");return;}
 if(source!==video){await savePng();status("動画またはカメラを選ぶとMotion Cardを作れます。今回はPNGを保存しました");return;}
 setBusy(true);let capture,timeout,error=null;const chunks=[];try{
 readSettings();if(!stream){video.pause();if(video.currentTime!==0){await new Promise((resolve,reject)=>{video.onseeked=resolve;video.onerror=()=>reject(Error("動画を先頭へ戻せません"));video.currentTime=0;});}await video.play();}
 render();capture=output.captureStream(15);recorder=new MediaRecorder(capture,{mimeType:type});const active=recorder;
 await new Promise((resolve,reject)=>{active.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};active.onerror=e=>{error=e.error||Error("録画に失敗しました");if(active.state!=="inactive")active.stop();};active.onstop=resolve;active.onstart=()=>{try{status("録画中 / "+recordingFormat(active.mimeType).label);}catch(e){error=e;stopRecording();}};video.onended=stopRecording;video.loop=false;active.start();timeout=setTimeout(stopRecording,Math.min(5,recipe.motion.seconds,stream?5:video.duration)*1000);});
 if(error)throw error;if(!chunks.length)throw Error("録画データが空です");const format=recordingFormat(active.mimeType||chunks[0].type),blob=new Blob(chunks,{type:active.mimeType||chunks[0].type});if(resultUrl)URL.revokeObjectURL(resultUrl);resultUrl=URL.createObjectURL(blob);const link=$("result");link.href=resultUrl;link.download="motion-card."+format.extension;link.textContent=format.label+"作品を保存";link.hidden=false;download(blob,link.download);status(format.label+"を保存しました。再保存リンクも利用できます");
 }catch(e){await savePng();status(e.message+"。PNGを保存しました");}finally{clearTimeout(timeout);capture?.getTracks().forEach(t=>t.stop());recorder=null;video.onended=null;video.onseeked=null;if(!stream){video.loop=true;if(source===video&&!document.hidden)video.play().catch(e=>status(e.message));}setBusy(false);}
});
document.addEventListener("visibilitychange",()=>{if(document.hidden){loading++;stopRecording();stopInput();source=sample;}});
window.addEventListener("pagehide",()=>{loading++;stopRecording();stopInput();if(resultUrl)URL.revokeObjectURL(resultUrl);});
let recipeError=null;try{if(location.hash.startsWith("#recipe="))recipe=decodeRecipe(location.hash.slice(8));}catch(e){recipeError=e.message;}
applySettings();sampleImage();if(recipeError)status(recipeError+"。標準設定でサンプルを表示しています");document.fonts?.ready.then(render);
