TVA_FORMAT = "TVA"
TVA_FORMAT_NAME = "Text Video Art"
TVA_VERSION = "0.1.0"
MAX_FRAME_COUNT = 1_000_000
MAX_FRAME_INDEX = 999_999

DEFAULT_CHARSET = " .:-=+*#%@"
DEFAULT_WIDTH = 100
DEFAULT_FPS = 10.0
DEFAULT_ASPECT_CORRECTION = 0.5

MANIFEST_NAME = "manifest.json"
FRAMES_PATH = "frames/"
